// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://euyqbmnbxirohyuzfboe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1eXFibW5ieGlyb2h5dXpmYm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4MDI4ODMsImV4cCI6MjA4NTM3ODg4M30.XBVKsLri8gSmshm4gKiBh6t1mRPnjWb7PwvJkVrye8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
